
[[Snippets]]
  Description = "Scan dir for something which looks like api keys"
  Filename = "/home/josh/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "grep -r -E '(api_key|secret|token|[A-Za-z0-9]{20,})' <path_to_dir>"

[[Snippets]]
  Description = "Add / re-add all files in a directory"
  Filename = "/home/josh/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "chezmoi add -r <path_to_dir>/*"

[[Snippets]]
  Description = "Compile sketch for ESP32"
  Filename = "/home/josh/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "arduino-cli compile --fqbn esp32:esp32:esp32 <path_to_file>"

[[Snippets]]
  Description = "Upload compiled sketch over serial USB"
  Filename = "/home/josh/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "arduino-cli upload -p /dev/ttyUSB0 --fqbn esp32:esp32:esp32 <path_to_file>"
