# ~/.config/starship.toml

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = "[â–¸â–¹ ](dimmed white)"

# Add the below two above $sudo\ to add a seperator line and line break
# $fill
# $line_break
format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$line_break\
$character\
"""

right_format = """
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$cmd_duration\
$status\
$battery\
$time\
"""

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# [fill]
# symbol = "-"
# style = "bold overlay0"

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "ğŸ¦¸"
disabled = false

[os]
format = "[$symbol]($style)"
style = "bold blue"
disabled = false

[os.symbols]
Linux = "ğŸ§"
Windows = "ğŸªŸ"
Macos = "ğŸ"
Ubuntu = "â­•"
Arch = "ğŸ«"
CentOS = "ğŸ’µ"
Debian = "ğŸŒ€"
Fedora = "ğŸ‘’"
Alpine = "ğŸ”ï¸"
SUSE = "ğŸ¦"
Redhat = "ğŸ©"

[username]
style_user = "bold italic blue"
style_root = "bold italic red"
format = "[$user]($style) "
show_always = true

[hostname]
ssh_only = false
style = "bold italic yellow"
format = "on [$hostname]($style) "
disabled = false

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold italic cyan"
format = "in [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "ğŸŒ¿ "
format = "on [$symbol$branch(:$remote_branch)]($style) "
style = "bold italic purple"
truncation_symbol = "..."
truncation_length = 11

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold italic green"

# Languages and Dev Tools
[deno]
format = "ğŸ¦• [deno](italic) [âˆ« $version](green bold) â”‚"
version_format = "${raw}"

[lua]
format = "ğŸŒ™ [lua](italic) [${symbol}${version}]($style) â”‚"
version_format = "${raw}"
symbol = " "
style = "bold bright-yellow"

[nodejs]
format = "ğŸŸ¢ [node](italic) [â—« ($version)](bold bright-green) â”‚"
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[python]
format = "ğŸ [py](italic) [${symbol}${version}]($style) â”‚"
symbol = "[âŒ‰](bold bright-blue)âŒŠ "
version_format = "${raw}"
style = "bold bright-yellow"

[ruby]
format = "ğŸ’ [rb](italic) [${symbol}${version}]($style) â”‚"
symbol = " "
version_format = "${raw}"
style = "bold red"

[rust]
format = "ğŸ¦€ [rs](italic) [$symbol$version]($style) â”‚"
symbol = " "
version_format = "${raw}"
style = "bold red"

[package]
format = "ğŸ“¦ [pkg](italic dimmed) [$symbol$version]($style) â”‚"
version_format = "${raw}"
symbol = " "
style = "dimmed yellow italic bold"

[swift]
format = "ğŸ [sw](italic) [${symbol}${version}]($style) â”‚"
symbol = " "
style = "bold bright-red"
version_format = "${raw}"

[aws]
disabled = true
format = "â˜ï¸ [aws](italic) [$symbol $profile $region]($style) â”‚"
style = "bold blue"
symbol = " "

[buf]
symbol = "ğŸƒ "
format = "[buf](italic) [$symbol $version $buf_version]($style) â”‚"

[c]
symbol = "ğŸ…’ "
format = "[$symbol($version(-$name))]($style) â”‚"

[conda]
symbol = "ğŸ "
format = "conda [$symbol$environment]($style) â”‚"

[dart]
symbol = "ğŸ¯ "
format = "dart [$symbol($version )]($style) â”‚"

[docker_context]
symbol = "ğŸ³ "
format = "docker [$symbol$context]($style) â”‚"

[elixir]
symbol = "ğŸ’§ "
format = "exs [$symbol $version OTP $otp_version ]($style) â”‚"

[elm]
symbol = "ğŸŒ³ "
format = "elm [$symbol($version )]($style) â”‚"

[golang]
symbol = "ğŸ¹ "
format = "go [$symbol($version )]($style) â”‚"

[haskell]
symbol = "Î» "
format = "hs [$symbol($version )]($style) â”‚"

[java]
symbol = "â˜• "
format = "java [${symbol}(${version} )]($style) â”‚"

[julia]
symbol = "à®ƒ "
format = "jl [$symbol($version )]($style) â”‚"

[memory_usage]
symbol = "ğŸ§  "
format = "mem [${ram}( ${swap})]($style) â”‚"

[nim]
symbol = "ğŸ‘‘ "
format = "nim [$symbol($version )]($style) â”‚"

[nix_shell]
style = 'bold italic dimmed blue'
symbol = 'â„ï¸ '
format = '[$symbol nixâª$stateâª]($style) [$name](italic dimmed white) â”‚'
impure_msg = '[âŒ½](bold dimmed red)'
pure_msg = '[âŒ¾](bold dimmed green)'
unknown_msg = '[â—Œ](bold dimmed yellow)'

[spack]
symbol = "ğŸ’ "
format = "spack [$symbol$environment]($style) â”‚"

[time]
disabled = false
time_format = "%R"
style = "bold white"
format = "â²ï¸ [$time]($style)"

[cmd_duration]
format = "â±ï¸ took [$duration ](bold yellow)"

[line_break]
disabled = false

[character]
format = "$symbol"
success_symbol = "[> ](bold green)"
error_symbol = "[> ](bold red)"
